mqtt:
  enabled: false

auth:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolo-generic
  path: /openvino-model/yolov8n/yolov8n_openvino_model/yolov8n.xml
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr

record:
  enabled: true
  continuous:
    days: 30
  motion:
    days: 30
cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/person-bicycle-car-detection.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    detect:
      height: 1080
      width: 1920
      fps: 5
version: 0.17-0
