mqtt:
  enabled: false

auth:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolo-generic
  path: /openvino-model/yolov8n/yolov8n_openvino_model/yolov8n.xml
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr

record:
  enabled: true
  continuous:
    days: 30
  motion:
    days: 30

objects:
  track:
    - person
    - car
    - truck
    - motorcycle
    - dog
    - cat
    - deer
    - bear
    - package

go2rtc:
  streams:
    doorbell_1:
      - ffmpeg:http://192.168.40.100/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=July122010#video=copy#audio=copy#audio=opus
    doorbell_2:
      - ffmpeg:http://192.168.40.100/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=July122010
    front_door_1:
      - rtsp://admin:July122010@192.168.40.70:554/cam/realmonitor?channel=1&subtype=0&unicast=true
    front_door_2:
      - rtsp://admin:July122010@192.168.40.70:554/cam/realmonitor?channel=1&subtype=1&unicast=true
    garage_1:
      - rtsp://admin:July122010@192.168.40.67:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_2:
      - rtsp://admin:July122010@192.168.40.67:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    driveway_1:
      - ffmpeg:rtsp://admin:July122010@192.168.40.65:554/h265Preview_01_main#video=h264
    driveway_2:
      - rtsp://admin:July122010@192.168.40.65:554/h264Preview_01_sub
    shop_inside_1:
      - ffmpeg:http://192.168.40.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=July122010#video=copy#audio=copy#audio=opus
    shop_inside_2:
      - ffmpeg:http://192.168.40.50/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=July122010
    shop_front_1:
      - rtsp://admin:July122010@192.168.40.60:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    shop_front_2:
      - rtsp://admin:July122010@192.168.40.60:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    shop_side_1:
      - rtsp://admin:July122010@192.168.40.55:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    shop_side_2:
      - rtsp://admin:July122010@192.168.40.55:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    patio_1:
      - rtsp://admin:July122010@192.168.40.85:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    patio_2:
      - rtsp://admin:July122010@192.168.40.85:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    firepit_1:
      - rtsp://admin:July122010@192.168.40.80:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    firepit_2:
      - rtsp://admin:July122010@192.168.40.80:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    mbr_1:
      - rtsp://admin:July122010@192.168.40.75:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    mbr_2:
      - rtsp://admin:July122010@192.168.40.75:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    behind_garage_1:
      - rtsp://admin:July122010@192.168.40.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    behind_garage_2:
      - rtsp://admin:July122010@192.168.40.90:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    speakeasy_1:
      - rtsp://admin:July122010@192.168.40.105:554/Preview_01_main
    speakeasy_2:
      - rtsp://admin:July122010@192.168.40.105:554/Preview_01_sub

cameras:
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - package
    live:
      streams:
        Stream 1: doorbell_1
        Stream 2: doorbell_2

    zones:
      front_porch:
        coordinates: 
          0.641,0.665,0.316,0.637,0.057,0.744,0.009,0.888,0.066,1,0.394,1,0.471,0.831,0.64,0.853
        loitering_time: 0
        objects: person
        friendly_name: Front Porch
        inertia: 3
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - package
    live:
      streams:
        Stream 1: front_door_1
        Stream 2: front_door_2

    zones:
      front_porch_top_view:
        coordinates: 
          0.324,0.388,0.58,0.024,0.706,0.108,0.901,0.243,0.769,0.821,0.651,0.807,0.562,0.974,0.473,1,0.306,0.8,0.371,0.522
        loitering_time: 0
        objects: person
        friendly_name: Front Porch Top View
        inertia: 3
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garage_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
    live:
      streams:
        Stream 1: garage_1
        Stream 2: garage_2

    zones:
      front_of_garage:
        coordinates: 0.915,0.363,0.811,0.992,0.002,0.992,0,0.604,0.397,0.362
        loitering_time: 0
        friendly_name: Front of Garage
      deer_in_front:
        coordinates: 
          0.072,0.54,0.177,0.419,0.43,0.258,0.547,0.182,0.724,0.148,0.912,0.345,0.403,0.354
        loitering_time: 0
        objects: motorcycle
        friendly_name: Deer in front
      wildlife_in_front:
        coordinates: 
          0.003,0.587,0.003,0.495,0.13,0.372,0.473,0.191,0.72,0.15,0.246,0.386
        loitering_time: 0
        objects: motorcycle
        friendly_name: Wildlife in front
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/driveway_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
    live:
      streams:
        Stream 1: driveway_1
        Stream 2: driveway_2

    zones:
      car_in_driveway:
        coordinates: 
          0.258,0.284,0.543,0.164,0.575,0.096,0.616,0.096,0.621,0.142,0.902,0.255,0.9,0.424
        loitering_time: 0
        objects: car
        friendly_name: Car in driveway
      wildlife_in_driveway_camera:
        coordinates: 
          0.251,0.27,0.248,0.157,0.53,0.084,0.868,0.106,0.906,0.241,0.82,0.971,0.013,0.983,0.009,0.566,0.265,0.402
        loitering_time: 0
        objects: motorcycle
        friendly_name: Wildlife in driveway camera
  shop_inside:
    enabled: true
    friendly_name: Shop Inside
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shop_inside_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/shop_inside_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
    live:
      streams:
        Stream 1: shop_inside_1
        Stream 2: shop_inside_2

  shop_front:
    enabled: true
    friendly_name: Shop Front
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shop_front_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/shop_front_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
    live:
      streams:
        Stream 1: shop_front_1
        Stream 2: shop_front_2

    zones:
      car_from_shop_front:
        coordinates: 
          0.781,0.986,0.629,0.993,0.128,0.202,0.004,0.139,0.019,0.121,0.132,0.152,0.431,0.199,0.717,0.303,0.886,0.401,0.89,0.475,0.806,0.419,0.634,0.46,0.875,0.657
        loitering_time: 0
        friendly_name: Car from Shop Front
      wildlife_from_shop_front:
        coordinates: 
          0.011,0.482,0.017,0.143,0.192,0.072,0.494,0.153,0.718,0.235,0.496,0.218
        loitering_time: 0
        friendly_name: Wildlife from Shop Front
  shop_side:
    enabled: true
    friendly_name: Shop Side
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shop_side_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/shop_side_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - bear
    live:
      streams:
        Stream 1: shop_side_1
        Stream 2: shop_side_2

    zones:
      wildlife_at_shop_side:
        coordinates: 
          0.007,0.978,0.013,0.292,0.16,0.155,0.459,0.134,0.771,0.132,0.917,0.231,0.866,0.684,0.796,0.984
        loitering_time: 0
        friendly_name: Wildlife at Shop Side
  patio:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/patio_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
    live:
      streams:
        Stream 1: patio_1
        Stream 2: patio_2

    zones:
      wildlife_from_patio:
        coordinates: 
          0.003,0.986,0.011,0.581,0.318,0.271,0.364,0.267,0.989,0.375,0.985,0.989
        loitering_time: 0
        friendly_name: Wildlife from Patio
  firepit:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/firepit_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/firepit_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - bear
        - deer
    live:
      streams:
        Stream 1: firepit_1
        Stream 2: firepit_2

    zones:
      wildlife_from_firepit:
        coordinates: 0.122,0.982,0.375,0.065,0.611,0.007,0.99,0.078,0.992,0.987
        loitering_time: 0
        friendly_name: Wildlife from Firepit
  mbr:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mbr_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/mbr_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - deer
    live:
      streams:
        Stream 1: mbr_1
        Stream 2: mbr_2

    zones:
      wildlife_from_mbr:
        coordinates: 
          0.391,0.989,0.296,0.377,0.404,0.108,0.54,0.002,0.992,0.005,0.989,0.984
        loitering_time: 0
        friendly_name: Wildlife from MBR
  behind_garage:
    enabled: true
    friendly_name: Behind Garage
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/behind_garage_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/behind_garage_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
    live:
      streams:
        Stream 1: behind_garage_1
        Stream 2: behind_garage_2

    zones:
      behind_garage_area:
        coordinates: 0.502,0.984,0.647,0.791,0.544,0.5,0.659,0.453,0.896,0.973
        loitering_time: 0
        objects: person
        friendly_name: Behind Garage Area
  speakeasy:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/speakeasy_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/speakeasy_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
    live:
      streams:
        Stream 1: speakeasy_1
        Stream 2: speakeasy_2

version: 0.17-0
